"""Write RASAero II CDX1 files from the intermediate geometry schema."""

from __future__ import annotations

import warnings
from pathlib import Path
from typing import Any
from xml.dom import minidom
from xml.etree import ElementTree as ET


IN_PER_M = 39.37007874015748


def write_rasaero_cdx1(model: dict[str, Any], output_path: str | Path) -> Path:
    """Write a single-stage RASAero II `.CDX1` model."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    root = ET.Element("RASAeroDocument")
    _text(root, "FileVersion", "2")

    design = ET.SubElement(root, "RocketDesign")
    _write_nose(design, model)
    # Parts in station order, every one of them. RASAero indexes its part
    # list positionally and places fins against a running length that a
    # tube and a transition advance and a boattail does not, so a
    # reduction with anything after it is written as a <Transition> -- the
    # same Reducer to the solver -- and only a trailing one as a
    # <BoatTail>. Only the first tube used to be written: a vehicle that
    # stepped down to a narrower motor tube lost that tube, and its fins
    # were clamped to the wrong one, 0.8 m forward on the boattail
    # demonstrator, which its own table then called 2.7 calibres unstable.
    sections = list(model.get("body_sections", []))
    tubes: list[tuple[ET.Element, float, float]] = []
    boattails: list[tuple[ET.Element, float, float]] = []
    for index, section in enumerate(sections):
        kind = section.get("type")
        start = float(section.get("start", 0.0))
        end = start + float(section.get("length", 0.0))
        if kind == "tube":
            tubes.append((_write_body(design, model, section, fittings=not tubes), start, end))
        elif kind == "transition":
            _write_transition(design, section)
        elif kind == "boattail":
            if index < len(sections) - 1:
                _write_transition(design, section)
            else:
                boattails.append((_write_boattail(design, section), start, end))
    if not tubes:
        nose_length = float(model["nose"].get("length", 0.0)) + float(model["nose"].get("start", 0.0))
        stub = {"start": nose_length, "length": 0.001}
        tubes.append((_write_body(design, model, stub, fittings=True), nose_length, nose_length + 0.001))
    if model.get("fins"):
        fin = model["fins"][0]
        _write_fin(_fin_parent(tubes, boattails, fin), fin)
    _write_protuberance(tubes[0][0], model.get("protuberances") or {})

    metadata = model.get("metadata", {}).get("source_metadata", {})
    _text(design, "Surface", str(metadata.get("surface", "Smooth Paint")))
    _text(design, "CP", "0")
    _text(design, "ModifiedBarrowman", str(bool(metadata.get("modified_barrowman", True))))
    _text(design, "Turbulence", str(bool(metadata.get("all_turbulent", True))))
    nozzle_dia = _num(metadata.get("sustainer_nozzle_diameter_m", 0.0), scale=IN_PER_M)
    _text(design, "SustainerNozzle", nozzle_dia)
    _text(design, "Booster1Nozzle", "0")
    _text(design, "Booster2Nozzle", "0")
    _text(design, "UseBooster1", "False")
    _text(design, "UseBooster2", "False")
    _text(
        design,
        "Comments",
        "Generated by Mudline step_to_rasaero. Verify geometry in RASAero II before using exported coefficients.",
    )

    _write_launch_site(root, metadata)
    _write_recovery(root, metadata)
    ET.SubElement(root, "MachAlt")
    _write_simulation(root, model, metadata)

    xml = ET.tostring(root, encoding="utf-8")
    pretty = minidom.parseString(xml).toprettyxml(indent="  ")
    pretty = "\n".join(line for line in pretty.splitlines() if line.strip())
    if pretty.startswith("<?xml"):
        pretty = "\n".join(pretty.splitlines()[1:])
    output_path.write_text(pretty + "\n", encoding="utf-8")
    return output_path


def _write_nose(parent: ET.Element, model: dict[str, Any]) -> None:
    nose = model["nose"]
    elem = ET.SubElement(parent, "NoseCone")
    _text(elem, "PartType", "NoseCone")
    _text(elem, "Length", _num(nose["length"], scale=IN_PER_M))
    _text(elem, "Diameter", _num(nose["base_diameter"], scale=IN_PER_M))
    _text(elem, "Shape", _rasaero_nose_shape(str(nose.get("type", "Tangent Ogive"))))
    _text(elem, "BluntRadius", _num(nose.get("blunt_radius", 0.0), scale=IN_PER_M))
    # The tip is RASAero's origin; the canonical model rebases every other
    # station on it before it gets here.
    _text(elem, "Location", _num(nose.get("start", 0.0), scale=IN_PER_M))
    _text(elem, "Color", "Black")


def _write_body(parent: ET.Element, model: dict[str, Any], section: dict[str, Any],
                fittings: bool = True) -> ET.Element:
    """One body tube. The fittings -- lug, guide, shoe -- ride on the first."""
    elem = ET.SubElement(parent, "BodyTube")
    _text(elem, "PartType", "BodyTube")
    _text(elem, "Length", _num(section["length"], scale=IN_PER_M))
    _text(elem, "Diameter", _num(section.get("diameter", model["rocket"]["max_diameter"]), scale=IN_PER_M))
    # Fittings ride on the body tube. RASAero reads the lug, guide and shoe as
    # plain child tags and the streamlined bodies and plates from a
    # <Protuberance> block emitted after the fins -- see aeroengine/cdx1.py,
    # which follows RASAero's own emission order because several drag terms
    # index the part list positionally.
    prot = (model.get("protuberances") or {}) if fittings else {}
    _text(elem, "LaunchLugDiameter", _num(prot.get("launch_lug_diameter_m", 0.0), scale=IN_PER_M))
    _text(elem, "LaunchLugLength", _num(prot.get("launch_lug_length_m", 0.0), scale=IN_PER_M))
    _text(elem, "RailGuideDiameter", _num(prot.get("rail_guide_diameter_m", 0.0), scale=IN_PER_M))
    _text(elem, "RailGuideHeight", _num(prot.get("rail_guide_height_m", 0.0), scale=IN_PER_M))
    _text(elem, "LaunchShoeArea", _num(prot.get("launch_shoe_area_m2", 0.0), scale=IN_PER_M ** 2))
    _text(elem, "Location", _num(section["start"], scale=IN_PER_M))
    _text(elem, "Color", "Black")
    # The boattail is its own <BoatTail> part, as in RASAero's own files;
    # it used to be written here as well, so RASAero saw it twice.
    _text(elem, "BoattailLength", "0")
    _text(elem, "BoattailRearDiameter", "0")
    _text(elem, "BoattailOffset", "0")
    _text(elem, "Overhang", "0")
    return elem


def _write_transition(parent: ET.Element, section: dict[str, Any]) -> ET.Element:
    """A change of diameter mid-body, in the form RASAero's *reader* wants.

    ``FrontDiameter`` is the front and ``Diameter`` the rear -- RASAero's
    own writer emits ``Diameter``/``RearDiameter``, which its reader cannot
    read back (see aeroengine/cdx1.py). A diameter-increasing transition
    used to be written as a <BoatTail>, so a payload bulge was solved as a
    taper: 15% off in drag and normal force supersonically.
    """
    elem = ET.SubElement(parent, "Transition")
    _text(elem, "PartType", "Transition")
    _text(elem, "Length", _num(section["length"], scale=IN_PER_M))
    _text(elem, "FrontDiameter", _num(section["front_diameter"], scale=IN_PER_M))
    _text(elem, "Diameter", _num(section["rear_diameter"], scale=IN_PER_M))
    _text(elem, "Location", _num(section["start"], scale=IN_PER_M))
    _text(elem, "Color", "Black")
    return elem


def _fin_parent(tubes: list, boattails: list, fin: dict[str, Any]) -> ET.Element:
    """The part a fin set hangs off: the tube it sits on, or the boattail.

    The tube whose span holds the fin's leading edge; failing that, a
    boattail that does; failing that, the last tube ahead of it, with a
    warning. A fin used to be clamped to the only tube written, wherever
    it actually was.
    """
    leading_edge_m = float(fin.get("axial_location", 0.0))
    for elem, start, end in tubes:
        if start - 1e-9 <= leading_edge_m <= end + 1e-9:
            return elem
    for elem, start, end in boattails:
        if start - 1e-9 <= leading_edge_m <= end + 1e-9:
            return elem
    ahead = [(elem, start) for elem, start, _ in tubes if start <= leading_edge_m]
    elem, start = max(ahead, key=lambda pair: pair[1]) if ahead else (tubes[0][0], tubes[0][1])
    warnings.warn(
        f"fin leading edge at {leading_edge_m:.3f} m lies on no tube or boattail; "
        f"written on the tube starting at {start:.3f} m.",
        stacklevel=2,
    )
    return elem


def _write_protuberance(parent: ET.Element, prot: dict[str, Any]) -> None:
    """The streamlined bodies and inclined plates, after the fins.

    RASAero writes the block whole or not at all, gated on any one of the four
    areas being non-zero, and its reader tolerates zero-area entries inside a
    present block. This mirrors that: no areas, no element -- which keeps the
    output byte-identical to before for every vehicle that has none.
    """
    areas = (
        prot.get("streamlined_no_base_area_m2", 0.0),
        prot.get("streamlined_with_base_area_m2", 0.0),
        prot.get("plate_area_m2", 0.0),
    )
    if not any(a > 0.0 for a in areas):
        return
    elem = ET.SubElement(parent, "Protuberance")
    _text(elem, "StreamlinedNoBaseDrag", _num(areas[0], scale=IN_PER_M ** 2))
    _text(elem, "StreamlinedWithBaseDrag", _num(areas[1], scale=IN_PER_M ** 2))
    _text(elem, "InclinedPlate1FrontalArea", _num(areas[2], scale=IN_PER_M ** 2))
    _text(elem, "InclinedPlate1Angle", _num(prot.get("plate_angle_deg", 90.0)))
    _text(elem, "InclinedPlate2FrontalArea", "0")
    _text(elem, "InclinedPlate2Angle", "0")


def _write_fin(parent: ET.Element, fin: dict[str, Any]) -> None:
    """Write a fin set onto its parent body tube.

    RASAero's ``Location`` for a fin is what its own dialog calls "Distance
    from the base of the tube": the gap between the *aft end* of the parent
    tube and the fin's leading edge at the root, measured forward. It was
    written here as the distance from the *front* of the tube instead, which
    mirrors every fin set about the tube's midpoint -- on a vehicle whose fins
    sit at the tail, that silently moves them to the nose end of the tube and
    drags the centre of pressure forward with them. On the reference rocket it
    put the fins 0.97 m out of place and reported a stable vehicle as 4.5
    calibres unstable.

    RASAero's own shipped example is the check: its sustainer tube spans
    15-63 in with a fin at 7 and a 7 in chord, which under this reading puts
    the fin's trailing edge exactly flush with the tube's base.
    """
    elem = ET.SubElement(parent, "Fin")
    tube_aft_in = _float_child(parent, "Location") + _float_child(parent, "Length")
    leading_edge_in = float(fin.get("axial_location", 0.0)) * IN_PER_M
    fin_location_in = tube_aft_in - leading_edge_in
    if fin_location_in < 0.0:
        warnings.warn(
            f"fin leading edge at {leading_edge_in / IN_PER_M:.3f} m is aft of its "
            f"parent's end at {tube_aft_in / IN_PER_M:.3f} m; RASAero cannot place "
            f"it there, so it is written at the parent's aft end.",
            stacklevel=2,
        )
        fin_location_in = 0.0
    thickness_in = max(float(fin.get("thickness", 0.0)) * IN_PER_M, 0.001)
    _text(elem, "Count", str(int(fin.get("count", 4))))
    _text(elem, "Chord", _num(fin.get("root_chord", 0.001), scale=IN_PER_M))
    _text(elem, "Span", _num(fin.get("span", 0.001), scale=IN_PER_M))
    _text(elem, "SweepDistance", _num(fin.get("sweep", 0.0), scale=IN_PER_M))
    _text(elem, "TipChord", _num(fin.get("tip_chord", fin.get("root_chord", 0.001)), scale=IN_PER_M))
    _text(elem, "Thickness", _format_float(thickness_in))
    _text(elem, "LERadius", "0")
    _text(elem, "Location", _format_float(fin_location_in))
    _text(elem, "AirfoilSection", str(fin.get("airfoil", "Hexagonal")))
    _text(elem, "FX1", _format_float(max(thickness_in * 2.0, 0.01)))
    _text(elem, "FX3", _format_float(max(thickness_in * 2.0, 0.01)))


def _write_boattail(parent: ET.Element, section: dict[str, Any]) -> ET.Element:
    elem = ET.SubElement(parent, "BoatTail")
    _text(elem, "PartType", "BoatTail")
    _text(elem, "Length", _num(section["length"], scale=IN_PER_M))
    _text(elem, "Diameter", _num(section["front_diameter"], scale=IN_PER_M))
    _text(elem, "RearDiameter", _num(section["rear_diameter"], scale=IN_PER_M))
    _text(elem, "Location", _num(section["start"], scale=IN_PER_M))
    _text(elem, "Color", "Black")
    return elem


def _write_launch_site(parent: ET.Element, metadata: dict[str, Any]) -> None:
    elem = ET.SubElement(parent, "LaunchSite")
    _text(elem, "Altitude", _num(metadata.get("launch_altitude_ft", 0.0)))
    _text(elem, "Pressure", _num(metadata.get("launch_pressure_inhg", 0.0)))
    _text(elem, "RodAngle", _num(metadata.get("launch_rod_angle_deg", 0.0)))
    _text(elem, "RodLength", _num(metadata.get("launch_rod_length_ft", 10.0)))
    _text(elem, "Temperature", _num(metadata.get("launch_temperature_f", 70.0)))
    _text(elem, "WindSpeed", _num(metadata.get("launch_wind_mph", 0.0)))


def _write_recovery(parent: ET.Element, metadata: dict[str, Any]) -> None:
    elem = ET.SubElement(parent, "Recovery")
    _text(elem, "Altitude1", _num(metadata.get("recovery_altitude1_ft", 1000.0)))
    _text(elem, "Altitude2", _num(metadata.get("recovery_altitude2_ft", 1000.0)))
    _text(elem, "DeviceType1", str(metadata.get("recovery_device1", "Parachute")))
    _text(elem, "DeviceType2", str(metadata.get("recovery_device2", "None")))
    _text(elem, "Event1", "True")
    _text(elem, "Event2", "False")
    _text(elem, "Size1", _num(metadata.get("recovery_size1_in", 36.0)))
    _text(elem, "Size2", "1")
    _text(elem, "EventType1", "Apogee")
    _text(elem, "EventType2", "None")
    _text(elem, "CD1", _num(metadata.get("recovery_cd1", 1.33)))
    _text(elem, "CD2", _num(metadata.get("recovery_cd2", 1.33)))


def _write_simulation(parent: ET.Element, model: dict[str, Any], metadata: dict[str, Any]) -> None:
    sim_list = ET.SubElement(parent, "SimulationList")
    sim = ET.SubElement(sim_list, "Simulation")
    _text(sim, "SustainerEngine", str(metadata.get("sustainer_engine", "None")))
    _text(sim, "SustainerLaunchWt", _num(metadata.get("launch_weight_lbf", 1.0)))
    nozzle = _num(metadata.get("sustainer_nozzle_diameter_m", 0.0), scale=IN_PER_M)
    _text(sim, "SustainerNozzleDiameter", nozzle)
    cg_m = float(metadata.get("cg_from_nose_m", model["rocket"]["length"] * 0.55))
    _text(sim, "SustainerCG", _num(cg_m, scale=IN_PER_M))
    _text(sim, "SustainerIgnitionDelay", "0")
    for tag in (
        "Booster1LaunchWt",
        "Booster1SeparationDelay",
        "Booster1IgnitionDelay",
        "Booster1CG",
        "Booster1NozzleDiameter",
    ):
        _text(sim, tag, "0")
    _text(sim, "IncludeBooster1", "False")
    for tag in ("Booster2LaunchWt", "Booster2Delay", "Booster2CG", "Booster2NozzleDiameter"):
        _text(sim, tag, "0")
    _text(sim, "IncludeBooster2", "False")
    for tag in ("FlightTime", "TimetoApogee", "MaxAltitude", "MaxVelocity", "OptimumWt", "OptimumMaxAlt"):
        _text(sim, tag, "0")


def _rasaero_nose_shape(value: str) -> str:
    lower = value.lower().replace("_", " ").replace("-", " ")
    if "conical" in lower:
        return "Conical"
    if "karman" in lower or "kármán" in lower:
        return "Von Karman Ogive"
    if "haack" in lower:
        return "LV-Haack"
    if "power" in lower:
        return "Power Law"
    if "parabolic" in lower:
        return "Parabolic"
    if "elliptic" in lower:
        return "Elliptical"
    return "Tangent Ogive"


def _text(parent: ET.Element, tag: str, value: object) -> ET.Element:
    elem = ET.SubElement(parent, tag)
    elem.text = str(value)
    return elem


def _num(value: object, scale: float = 1.0) -> str:
    try:
        return _format_float(float(value) * scale)
    except (TypeError, ValueError):
        return "0"


def _format_float(value: float) -> str:
    text = f"{value:.6g}"
    return "0" if text == "-0" else text


def _float_child(parent: ET.Element, tag: str) -> float:
    child = parent.find(tag)
    if child is None or child.text is None:
        return 0.0
    try:
        return float(child.text)
    except ValueError:
        return 0.0
