"""Freeze an oracle run into committed reference data.

``build/oracle`` is gitignored and regenerating it costs twenty minutes of
exclusive control of the desktop -- the driver synthesises keystrokes and
steals foreground, so nothing else can use the machine while it runs. That is
fine as an occasional deep check and unacceptable as a test dependency, so the
result is frozen here instead.

What gets committed is the parsed CSV, gzipped, plus the exact ``.CDX1`` that
produced it. Both matter. The CSV alone would let the engine drift against a
geometry nobody can reconstruct; the CDX1 alone would need RASAero to be
meaningful. Together they are a closed statement: *this file, run through
RASAero, gives these numbers.*

Full resolution is kept -- all 2500 Mach points -- because the whole set
compresses to a few megabytes and decimating it would leave gaps exactly where
a regression is most likely to hide, at the branch boundaries the sweep steps
across.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import shutil
from pathlib import Path

GOLDEN = Path(__file__).resolve().parent / "golden"
MANIFEST = GOLDEN / "manifest.json"


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def package(source: str | Path = "build/oracle", *, quiet: bool = False) -> int:
    """Copy an oracle build into ``oracle/golden``. Returns the case count."""
    source = Path(source)
    csv_dir = source / "csv"
    cdx1_dir = source / "cdx1"
    if not csv_dir.is_dir():
        raise FileNotFoundError(
            f"{csv_dir} does not exist -- run `python -m oracle.build` first"
        )

    (GOLDEN / "cdx1").mkdir(parents=True, exist_ok=True)
    entries = []

    for csv in sorted(csv_dir.glob("*.csv")):
        # Case names are "<vehicle>_a<alpha>"; the vehicle owns the geometry.
        stem = csv.stem
        vehicle, _, alpha_tag = stem.rpartition("_a")
        alpha = float(alpha_tag.replace("p", "."))

        cdx1 = cdx1_dir / f"{vehicle}.CDX1"
        if not cdx1.exists():
            if not quiet:
                print(f"  skipping {stem}: no {cdx1.name}")
            continue

        target_cdx1 = GOLDEN / "cdx1" / cdx1.name
        if not target_cdx1.exists():
            shutil.copyfile(cdx1, target_cdx1)

        gz = GOLDEN / f"{stem}.csv.gz"
        gz.write_bytes(gzip.compress(csv.read_bytes(), compresslevel=9))

        entries.append({
            "case": stem,
            "vehicle": vehicle,
            "alpha_deg": alpha,
            "cdx1": f"cdx1/{cdx1.name}",
            "cdx1_sha256_16": _digest(cdx1),
            "csv_gz": gz.name,
            "bytes_gz": gz.stat().st_size,
        })
        if not quiet:
            print(f"  {stem}: {gz.stat().st_size / 1024:.1f} KB")

    MANIFEST.write_text(json.dumps({
        "note": (
            "Generated by RASAero II 1.0.2.0 via Tools > Run Test. "
            "Regenerate with `python -m oracle.build` then `python -m oracle.package`."
        ),
        "cases": entries,
    }, indent=2), encoding="utf-8")

    total = sum(e["bytes_gz"] for e in entries)
    if not quiet:
        print(f"{len(entries)} cases, {total / 1e6:.2f} MB -> {GOLDEN}")
    return len(entries)


def load_manifest() -> list[dict]:
    if not MANIFEST.exists():
        return []
    return json.loads(MANIFEST.read_text(encoding="utf-8"))["cases"]


if __name__ == "__main__":  # pragma: no cover
    import sys

    package(sys.argv[1] if len(sys.argv) > 1 else "build/oracle")
