"""The project file: a vehicle and the analysis history that goes with it.

A vehicle on its own is not the whole of what a session produces. The runs
matter -- they are the record of what was tried and what it cost, and losing
them on close means the comparison feature only works within one sitting.

The format wraps the vehicle rather than replacing it, and loading accepts
either shape, so files written before this still open.

What is not saved
-----------------
Result payloads: a solve_ivp object, an aero database, a lofted solid. They are
large, they are derived, and they can be regenerated by re-running. Metrics,
settings and plottable series are kept, so a restored run can still be read and
compared -- it simply cannot be pushed back into the viewport as a trajectory.
Restored runs say so rather than offering a button that would not work.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import numpy as np

from app.results import Metric, Result, ResultStore
from parametric.model import VehicleModel

PROJECT_FORMAT = "mudline.project.v1"
#: Accepted on load as well: projects written before the rename.
LEGACY_PROJECT_FORMATS = ("rocket_model.project.v1",)


def result_to_dict(result: Result) -> dict:
    return {
        "index": result.index,
        "kind": result.kind,
        "label": result.label,
        "fingerprint": result.fingerprint,
        "timestamp": result.timestamp.isoformat(timespec="seconds"),
        "build": dict(result.build),
        "settings": dict(result.settings),
        "metrics": [
            {
                "label": m.label, "value": float(m.value), "unit": m.unit,
                "decimals": m.decimals, "higher_is_better": m.higher_is_better,
            }
            for m in result.metrics
        ],
        "series": {
            name: {
                "x": np.asarray(entry[0], dtype=float).tolist(),
                "y": np.asarray(entry[1], dtype=float).tolist(),
                "x_label": entry[2] if len(entry) > 2 else "",
                "y_label": entry[3] if len(entry) > 3 else "",
            }
            for name, entry in result.series.items()
        },
    }


def result_from_dict(data: dict) -> Result:
    return Result(
        index=int(data.get("index", 0)),
        kind=data.get("kind", "unknown"),
        label=data.get("label", "Result"),
        fingerprint=data.get("fingerprint", ""),
        timestamp=datetime.fromisoformat(
            data.get("timestamp", datetime.now().isoformat(timespec="seconds"))
        ),
        build=dict(data.get("build", {})),
        settings=dict(data.get("settings", {})),
        metrics=[
            Metric(
                label=m["label"], value=float(m["value"]), unit=m.get("unit", ""),
                decimals=int(m.get("decimals", 3)),
                higher_is_better=m.get("higher_is_better"),
            )
            for m in data.get("metrics", [])
        ],
        series={
            name: (
                np.array(entry["x"], dtype=float),
                np.array(entry["y"], dtype=float),
                entry.get("x_label", ""),
                entry.get("y_label", ""),
            )
            for name, entry in data.get("series", {}).items()
        },
        # Marked so the panel can tell a restored run from a live one: its
        # trajectory is gone and cannot be shown.
        payload={"restored": True},
    )


def _build_provenance() -> dict[str, str]:
    try:
        from app.version import provenance

        return provenance()
    except Exception:      # noqa: BLE001 - a save must not fail over a label
        return {}


def save_project(path: str | Path, model: VehicleModel,
                 results: ResultStore | None = None) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "format": PROJECT_FORMAT,
        "saved": datetime.now().isoformat(timespec="seconds"),
        # Which build wrote this. A project file is the thing that travels
        # between people, so it is the thing that has to be able to say what
        # made it -- otherwise two colleagues comparing apogees have no way to
        # tell a design difference from a code difference.
        "app": _build_provenance(),
        "vehicle": model.to_dict(),
        "results": [result_to_dict(r) for r in (results or [])],
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def load_project(path: str | Path) -> tuple[VehicleModel, list[Result]]:
    """Read a project, or a bare vehicle file written before projects existed."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))

    if data.get("format") in (PROJECT_FORMAT, *LEGACY_PROJECT_FORMATS):
        model = VehicleModel.from_dict(data["vehicle"])
        results = [result_from_dict(entry) for entry in data.get("results", [])]
        return model, results

    # A plain vehicle file: still perfectly valid input.
    return VehicleModel.from_dict(data), []


@dataclass
class DocumentState:
    """Where the document lives and whether it has unsaved changes."""

    path: Path | None = None
    dirty: bool = False

    @property
    def title(self) -> str:
        name = self.path.name if self.path else "untitled"
        return f"{name}{'*' if self.dirty else ''}"

    def mark_dirty(self) -> None:
        self.dirty = True

    def mark_saved(self, path: Path) -> None:
        self.path = Path(path)
        self.dirty = False


def autosave_path(path: Path | None, name: str) -> Path:
    """Where an autosave goes.

    Beside the document when there is one, so it is found next to the work it
    belongs to; otherwise in the user's temp directory, because an untitled
    document has nowhere else to live and losing it is the case autosave exists
    for.
    """
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in name).strip("_")
    if path is not None:
        return path.with_name(f".{path.stem}.autosave.json")
    import tempfile

    directory = Path(tempfile.gettempdir()) / "mudline"
    directory.mkdir(parents=True, exist_ok=True)
    return directory / f"{safe or 'untitled'}.autosave.json"
